---
image: ruby:2.6

cache:
  paths:
    - vendor/bundle

variables:
  BUNDLE_PATH: vendor/bundle

.beforescript: &beforescript
  - apt-get update
  - apt-get install -y libpcap-dev
  - bundle check || bundle install

pages:
  before_script:
    - *beforescript
  script:
    - bundle exec yardoc "*.rb"
    - mv doc/ public/
  artifacts:
    paths:
      - public
